### ISSUE TITLE
后台显示是怎么做的呢

### ISSUE THREAD

**Issue by TencentPlayer** [dingxiaowei/MonitorTool#1]
看代码没找到后台显示相关呢

**Comment by dingxiaowei** [comment]
开源的是前端的，后台的暂时还没开源，后台是.net开发的

**Comment by dingxiaowei** [comment]
需要的话 可以私下发你

**Comment by LyonGu** [comment]
> 需要的话 可以私下发你

您好，也请发给我学习下，邮箱是lyonsgu@163.com，感谢！

**Comment by gaozhou** [comment]
> 需要的话 可以私下发你

 给我发一份， grimmzzf@gmail.com

**Comment by avi6111** [comment]
> 需要的话 可以私下发你

大哥，现在还有维护么，发一份后台，谢谢, avi9111@163.com

**Comment by itismyera** [comment]
大哥，求发一份后台，谢谢！  745368206@qq.com
